---
title: "DataEntry"
output: html_document
---

#########################################################################################################
Package load and retrieval
#########################################################################################################
```{r,warning=F}
#necessary packages: 
pack_list<-list ("ggplot2","openair","dygraphs","xts","dataRetrieval","dplyr","forecast","glue")
for(i in 1:length(pack_list)){
  p <- pack_list[[i]]
  install.packages(p,repos = "https://cran.rstudio.com",dependencies = TRUE)
}

install.packages("devtools")
install.packages("dataRetrieval", repos=c("http://owi.usgs.gov/R",getOption("repos")))
library(devtools)
```

#########################################################################################################
NUTRIENT Data input from .csv and STROUD RESEARCH server. File is named as Valett Lab output.
------WorkDirectory and Filename may need to be changed
------File include date, site, replicate, concenration  
#########################################################################################################
```{r setup, include=FALSE}
library(dplyr)
setwd("C:/Users/admin/Dropbox/LTREB_UCFR_nutrient data")
nitrate_series = read.csv("nitrate_series.csv"); tail(nitrate_series,1)
nitrate_series2 = read.csv("nitrate_Jan2017_Jul2019.csv") ; head(nitrate_series2,1)
nitrate_series = rbind(nitrate_series,nitrate_series2)
write.csv(nitrate_series, file = "nitrate_series.csv")
```

##################################################################
DISCHARGE data input via URL from USGS using dataRetrieval package
##################################################################
```{r}
library(dataRetrieval)#check station code online (usually an 8-15digit numebr)
###Input request specifications:
siteNo <- "12323800" #Site 2; Clark Fork near Galen MT - 12323800
pCode <- "00060"
start.date <- "2017-08-01"
end.date <- "2019-08-01" #----------------------------------------------change end date accordingly
####retrieve daily average Q
        q_daily <- readNWISdv(siteNumbers = siteNo, 
                            parameterCd = pCode, 
                            startDate = start.date, 
                            endDate = end.date) 
Site2_Q = q_daily###Input request specifications:

siteNo <- "12324200" #Site 6; Clark Fork at Deer Lodge MT - 12324200
        q_daily <- readNWISdv(siteNumbers = siteNo, 
                            parameterCd = pCode, 
                            startDate = start.date, 
                            endDate = end.date) 
Site6_Q = q_daily

siteNo <- "12324400" #Site 8; Clark Fork ab Little Blackfoot R nr Garrison MT - 12324400
        q_daily <- readNWISdv(siteNumbers = siteNo, 
                            parameterCd = pCode, 
                            startDate = start.date, 
                            endDate = end.date) 
Site8_Q = q_daily

siteNo <- "12324680" #Site 9; Clark Fork at Goldcreek MT - 12324680
        q_daily <- readNWISdv(siteNumbers = siteNo, 
                            parameterCd = pCode, 
                            startDate = start.date, 
                            endDate = end.date) 
Site9_Q = q_daily

siteNo <- "12331800" #Site 10; Clark Fork near Drummond MT - 12331800
####retrieve daily average Q
        q_daily <- readNWISdv(siteNumbers = siteNo, 
                            parameterCd = pCode, 
                            startDate = start.date, 
                            endDate = end.date) 
Site10_Q = q_daily

siteNo <- "12334550" #Site 12; Clark Fork at Turah Bridge nr Bonner MT - 12334550
        q_daily <- readNWISdv(siteNumbers = siteNo, 
                            parameterCd = pCode, 
                            startDate = start.date, 
                            endDate = end.date) 
Site12_Q = q_daily

siteNo <- "12340500" #Site 13; Clark Fork above Missoula MT - 12340500
        q_daily <- readNWISdv(siteNumbers = siteNo, 
                            parameterCd = pCode, 
                            startDate = start.date, 
                            endDate = end.date) 
Site13_Q = q_daily

siteNo <- "12323850" #LostCreek; Lost Creek near Galen, MT - 12323850 
        q_daily <- readNWISdv(siteNumbers = siteNo, 
                            parameterCd = pCode, 
                            startDate = start.date, 
                            endDate = end.date) 
LostCreek_Q = q_daily

```  

#########################################################################################################
Calculate means and merge with Q data
Output is the final dataset to perform calculations
#########################################################################################################
```{r}
library(xts);library(tidyverse);library(forecast);library(glue)
detach(package:dplyr);library(dplyr)
nitrate_series$date<-as.Date(nitrate_series$date, format = "%m/%d/%Y") #output is YYYY-mm-dd
nitrate_series$concentration<-nitrate_series$concentration*1000 #change units to mg/m3
 daily_nitrate_series = nitrate_series %>% group_by(date, site) %>%
        summarise_at(vars(concentration), funs(mean(., na.rm = TRUE))) ###Average by date
                  daily_nitrate_series$concentration = round(daily_nitrate_series$concentration,1)  
                  daily_nitrate_series$concentration =  ifelse(daily_nitrate_series$concentration < 0, 1, daily_nitrate_series$concentration) ##Negative values are converted to low psotive numbers
                  
sub_sites <- c("s2", "s6","s8","s9","s10","s12","s13") 
daily_nitrate_Q_series = filter(daily_nitrate_series, site %in% sub_sites) #sites with USGS data

#pair each site with Q data, merge, and rbind in a unique data set
temp = filter(daily_nitrate_Q_series, site == "s2")
  qdata = Site2_Q[,3:4]
    colnames(qdata)<-c("date","Discharge")
      temp_s2 = merge(temp,qdata,by = c("date"))
      
temp = filter(daily_nitrate_Q_series, site == "s6")
  qdata = Site6_Q[,3:4]
    colnames(qdata)<-c("date","Discharge")
      temp_s6 = merge(temp,qdata,by = c("date"))
      
temp = filter(daily_nitrate_Q_series, site == "s8")
  qdata = Site8_Q[,3:4]
    colnames(qdata)<-c("date","Discharge")
      qdata[is.na(qdata)] <- 350 #to get rid of NA due to ice cover, value is typical for winter on this site
      temp_s8 = merge(temp,qdata,by = c("date"))
      
temp = filter(daily_nitrate_Q_series, site == "s9")
  qdata = Site9_Q[,3:4]
    colnames(qdata)<-c("date","Discharge")
      temp_s9 = merge(temp,qdata,by = c("date"))
      
temp = filter(daily_nitrate_Q_series, site == "s10")
  qdata = Site10_Q[,3:4]
    colnames(qdata)<-c("date","Discharge")
      temp_s10 = merge(temp,qdata,by = c("date"))
      
temp = filter(daily_nitrate_Q_series, site == "s12")
  qdata = Site12_Q[,3:4]
    colnames(qdata)<-c("date","Discharge")
      temp_s12 = merge(temp,qdata,by = c("date"))
      
temp = filter(daily_nitrate_Q_series, site == "s13")
  qdata = Site13_Q[,3:4]
    colnames(qdata)<-c("date","Discharge")
      temp_s13 = merge(temp,qdata,by = c("date"))
      
daily_nitrate_Q_series_merged = rbind(temp_s2,temp_s6,temp_s8,temp_s9,temp_s10,temp_s12,temp_s13)


```



